# Generated by Django 5.0.6 on 2024-07-01 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='flascard',
            new_name='flashcard',
        ),
    ]
